### PR TITLE
Unix time 2038 problem

### PR DESCRIPTION
**Pull request by MrMuminov**
| Q             | A
| ------------- | ---
| New feature?  | ✔️

### CODE REVIEW

**Comment by vjik** [comment]
Using `int` type for date don't have unix time 2038 problem.

**Comment by MrMuminov** [comment]
> Using `int` type for date don't have unix time 2038 problem.

What if working with db?
replace int with bigint?

**Comment by vjik** [comment]
> > Using `int` type for date don't have unix time 2038 problem.
> 
> What if working with db? replace int with bigint?

This is problem of implementation `AssignmentsStorageInterface` and `ItemsStorageInterface`. In concrete implementation we can convert `int` value to need format.

**Comment by MrMuminov** [comment]
> This is problem of implementation `AssignmentsStorageInterface` and `ItemsStorageInterface`. In concrete implementation we can convert `int` value to need format.

Sorry if I took your time
I got a great skill out of this job. (more precisely from these comments :)
Thank you. :)

**Pull request closed without merging**
